import type { DetectedLocation, LocationProfile } from "@shared/schema";

export const DEMO_LOCATIONS: DetectedLocation[] = [
  {
    name: "The Airwell",
    role: "Primary Setting",
    briefDescription:
      "An underground resistance command hub carved into the heart of an Appalachian mountain. A vast vertical shaft lined with salvaged technology, repurposed mine tunnels, and the last free broadcast transmitter in the eastern territories.",
    estimatedImportance: "major",
  },
  {
    name: "The Canopy Market",
    role: "Secondary Setting",
    briefDescription:
      "A sprawling black-market bazaar suspended in the forest canopy above the Airwell's surface entrance. Rope bridges, tarp-covered platforms, and barter stalls where resistance fighters trade supplies and intelligence.",
    estimatedImportance: "major",
  },
  {
    name: "Sector 7 — New Pittsburgh",
    role: "Secondary Setting",
    briefDescription:
      "The nearest corporate-controlled city, a surveillance-saturated megalopolis built on the ruins of old Pittsburgh. Its gleaming towers and enforced order contrast sharply with the wild freedom of the mountains.",
    estimatedImportance: "major",
  },
  {
    name: "The Throat",
    role: "Transitional",
    briefDescription:
      "A narrow, half-collapsed mine passage that serves as the only ground-level entry to the Airwell. Rigged with deadfalls and monitored by hidden sentries — the chokepoint that makes the base defensible.",
    estimatedImportance: "minor",
  },
  {
    name: "Ghost Ridge",
    role: "Symbolic",
    briefDescription:
      "A wind-scarred ridgeline above the Airwell where the original mining community was massacred during the Corporate Wars. Memorial cairns mark the dead. Characters go here to think, grieve, or make decisions.",
    estimatedImportance: "minor",
  },
  {
    name: "The Relay Tower",
    role: "Mentioned",
    briefDescription:
      "An abandoned fire-watch tower on a neighboring peak, retrofitted as a signal relay for the resistance's pirate radio network. Appears only in references and a single tense scene.",
    estimatedImportance: "background",
  },
];

export const DEMO_PROFILE: LocationProfile = {
  // Section 1: Location Identity
  logline:
    "The Airwell is an underground resistance command hub hidden inside an abandoned Appalachian coal mine — a vertical fortress where humanity's last free voices broadcast defiance into a corporate-controlled world.",
  type: "Interior (underground complex) with exterior approach zones — hybrid",
  scale: "Multi-level underground complex spanning roughly 200 vertical meters within a hollowed-out mountain, with surface camouflage extending across a half-mile of dense forest",
  timePeriod: "2089, forty years after the Corporate Consolidation Wars reshaped North America into corporate territories",
  alternateNames: "The Well, The Hole, Shaft Nine (its original mining designation), 'Home' (to the 200+ resistance members who live there)",

  // Section 2: Geography & Physical Layout
  region: "Southern Appalachian Mountains, in what was formerly West Virginia. The exact location is a closely guarded secret — coordinates are never spoken aloud, only transmitted via encrypted dead drops.",
  terrain: "Steep, heavily forested mountain terrain with exposed sandstone and shale cliffs. The mountain itself — locally called Blackbone Ridge — is riddled with abandoned coal mine shafts dating back to the 19th century.",
  climate: "Humid continental with harsh winters. Heavy fog rolls through the valleys most mornings, providing natural concealment. Annual rainfall feeds numerous small waterfalls that help mask the sound of the Airwell's ventilation systems.",
  elevation: "Surface entrance at approximately 1,200 meters. The main operations level sits at roughly 1,000 meters, carved into a natural limestone cavern. The lowest functional level — the generator room — descends to 800 meters.",
  layoutDescription: "The Airwell is organized around a central vertical shaft (the original mine ventilation shaft, widened to roughly 15 meters in diameter). Seven functional levels radiate outward from this shaft like the spokes of a wheel: Level 1 (top) — camouflaged surface access and defense positions. Level 2 — The Canopy (common area, mess hall, hydroponic gardens). Level 3 — Quarters (sleeping berths for 200+ carved into the rock). Level 4 — The Broadcast Level (radio equipment, the transmitter array, signal intelligence). Level 5 — Armory and training. Level 6 — Medical bay and the 'Archive' (a library of salvaged pre-war books and data). Level 7 (bottom) — Generators, water treatment, and the emergency escape tunnels.",
  entryExitPoints: "Primary: The Throat — a narrow, booby-trapped mine tunnel with three blast doors. Secondary: A concealed rope-and-pulley system accessible from a cliff face (emergency only). Tertiary: The Deep Exit — a flooded mine passage at Level 7 that connects to an underground river, usable only with rebreathers. The vertical shaft itself has a camouflaged top opening used for ventilation and, in emergencies, helicopter extraction.",
  surroundingEnvironment: "Dense Appalachian mixed-hardwood forest, old-growth in many areas since the Corporate Wars depopulated the region. Black bears, white-tailed deer, and feral dogs are common. The ruins of several coal-mining towns (abandoned since the 2040s) dot the surrounding valleys, providing scavenging sites.",
  nearestLandmarks: "Ghost Ridge (2 km north) — the memorial ridgeline. The Canopy Market (directly above the surface entrance). The ruins of the town of Coalvale (8 km southeast). The Relay Tower (12 km west, on a neighboring peak). Sector 7/New Pittsburgh (approximately 150 km northwest).",
  travelRoutes: "No roads lead to the Airwell — all surface approaches are on foot through unmarked forest trails that change seasonally. Supply runs to the Canopy Market use a network of zip lines and rope bridges through the canopy. Travel to New Pittsburgh requires a three-day overland journey or a risky flight in a salvaged drone transport.",

  // Section 3: History & Timeline
  originFounding: "The mine (Shaft Nine of the Blackbone Coal Company) was operational from 1923 to 2038, when the Corporate Wars made resource extraction unprofitable in contested Appalachian territories. The resistance discovered and converted it in 2071, led by the engineer Mara Calloway, who recognized the ventilation shaft's potential as both a defensible structure and a broadcast antenna.",
  keyHistoricalEvents: "1923 — Mine opens. 1947 — Explosion kills 34 miners (their names are carved into Level 6's walls). 2038 — Mine abandoned during Corporate Wars. 2071 — Resistance occupation begins under Mara Calloway. 2074 — First pirate radio broadcast ('The Voice of the Airwell') reaches Sector 7. 2081 — The Siege — corporate forces discover the Throat entrance; 17 defenders die holding the blast doors. 2085 — The Archive is established, becoming the largest repository of uncensored information east of the Mississippi.",
  previousUses: "Coal mine (1923–2038), briefly used as an illegal waste dump by a subsidiary of OmniCorp (2041–2044), abandoned and flooded (2044–2068), partially drained and explored by survivalist groups (2068–2071), converted to resistance base (2071–present).",
  whoBuiltItAndWhy: "The mine was built by the Blackbone Coal Company to extract bituminous coal. The resistance conversion was designed by Mara Calloway, a former OmniCorp structural engineer who defected after discovering the company's role in the Coalvale Massacre. She spent three years reinforcing the shaft, installing blast doors, and rigging the broadcast array.",
  currentStateVsOriginal: "The original mine was a utilitarian extraction site — dark, dangerous, disposable. The Airwell has transformed it into something between a fortress and a home. The rock walls are covered in murals, the mess hall has real tablecloths, and the hydroponic gardens fill Level 2 with green light. But the bones of the mine remain: you can still see coal seams in the walls, the 1947 memorial is preserved, and the deepest levels still flood during heavy rains.",
  echoingEvents: "The 1947 mine explosion echoes through the story — the Airwell's defenders see themselves as inheritors of the miners' sacrifice. The Siege of 2081 left physical scars (blast damage on Level 1, a sealed tunnel where three defenders are still entombed) and psychological ones — no one enters the Throat without remembering.",

  // Section 4: Sensory Profile
  defaultSounds: "The constant low hum of the ventilation fans (a sound residents stop noticing but visitors find unsettling). Dripping water, always — from condensation, from underground springs, from the ever-present moisture of deep rock. The echo of footsteps on metal grating. Distant voices carrying strangely through the shaft. And twice daily, the broadcast: the opening tones of the pirate radio signal that reverberates through every level.",
  smells: "Damp stone and mineral dust (the base note of everything). Machine oil and hot electronics from the broadcast equipment. The green, earthy scent of the hydroponic gardens on Level 2. Coffee — real coffee, the resistance's most precious luxury, brewed on Level 4 during broadcast shifts. Deeper down: stale air, rust, and the faint sulfur of old coal seams.",
  lightQuality: "Primarily artificial — warm LED strips along the main corridors (salvaged from pre-war buildings), harsh fluorescent in the workspaces, and the eerie blue-green of bioluminescent moss that has colonized the deeper, wetter tunnels. The only natural light enters through the camouflaged shaft opening at the top, creating a single column of daylight that shifts through the central shaft like a sundial. At dawn, it paints the upper levels gold; by afternoon, it's a pale gray pillar; at night, it becomes a circle of stars visible from Level 4.",
  temperatureAirQuality: "A constant 12°C (54°F) on most levels — cool enough to need a jacket, warm enough to survive. Humidity hovers around 80%, making everything feel slightly damp. Air quality varies by level: excellent near the ventilation shaft, stuffy in the deeper quarters, and occasionally dangerous in the sealed lower tunnels where methane can accumulate. The hydroponic gardens produce a noticeable oxygen boost on Level 2.",
  tactileSurfaces: "Rough-hewn rock walls with occasional smooth patches where water has polished the limestone over decades. Cold metal grating underfoot on the walkways. The wooden handrails along the central shaft — smooth from thousands of hands — are one of the few warm textures. Everything has a faint dampness. The blast doors are cold, heavy steel with rivets you can feel through gloves.",
  timeOfDayVariations: "The Airwell runs on its own clock — surface time matters less underground. But the shaft of daylight creates a natural rhythm: golden mornings when Level 2's gardens catch the light, gray afternoons when the broadcast level hums with activity, and quiet nights when the shaft shows stars and the generators shift to low-power mode. The twice-daily broadcast (0600 and 2100) structures the community's life more than sunrise or sunset.",

  // Section 5: Mood & Emotional Atmosphere
  defaultEmotionalTone: "Defiant hope undercut by claustrophobic tension. The Airwell feels like the last campfire in a dark forest — warm, alive, communal, but surrounded by enormous danger. There's a fierce pride in what the resistance has built here, tempered by the constant awareness that discovery means destruction.",
  psychologicalEffect: "The verticality is the dominant psychological feature. Looking up the shaft, you see light — freedom, the sky, escape. Looking down, you see darkness — depth, the weight of the mountain, the trapped feeling of being underground. Characters who arrive feel compressed, confined. Characters who've lived here feel protected, grounded. The transition from claustrophobia to security is a barometer of trust and belonging.",
  protagonistFeeling: "For Kira (the protagonist), the Airwell is simultaneously home and prison. She was born here — it's the only world she knows. She loves it fiercely and resents it completely. The broadcast level is her sanctuary (where she feels powerful and connected to the outside world), and Level 7 is her nightmare (where the deep darkness triggers her fear of being buried alive, inherited from the mining disaster stories).",
  appearsVsReality: "To outsiders and corporate intelligence, the Airwell is imagined as a crude hideout — desperate people cowering in a hole. The reality is a functioning community with governance, education, art, and purpose. It appears to be a bunker; it's actually a civilization in miniature.",
  locationLie: "The Airwell pretends to be invincible — the defenders' bravado, the blast doors, the booby-trapped Throat all project strength. The truth is that the base is slowly dying: the generators are failing, the deepest levels are flooding faster than pumps can clear, and the food supply depends on trade routes that corporate patrols are tightening. The mountain that protects them is also slowly crushing them.",

  // Section 6: Inhabitants & Social Structure
  whoLivesWorksHere: "Approximately 230 permanent residents: resistance fighters (about 80 combat-capable), technicians and engineers (40), broadcasters and signal operatives (15), medical staff (8), teachers (6), children (35), and elderly/non-combat residents (46). Plus a rotating population of 20–40 traders, scouts, and refugees passing through.",
  powerHierarchy: "Nominally democratic — a council of seven elected representatives. In practice, three figures hold real power: Commander Vasquez (military decisions), Mara Calloway (infrastructure, now elderly but still consulted on everything), and DJ Torch (the lead broadcaster, whose voice IS the resistance to the outside world and whose influence is enormous and unofficial).",
  writtenUnwrittenRules: "Written: rationing schedules, defense rotation duties, broadcast protocols, water usage limits. Unwritten: you don't touch another person's bunk space. You don't waste food — ever. You stand when the broadcast signal starts. You don't talk about Level 7 flooding to the children. New arrivals sleep on Level 1 (closest to the exit) until they're vouched for — nobody says why, but everyone knows it's so they can be expelled quickly if they're a spy.",
  territorialBoundaries: "Each level has its own culture. Level 4 (broadcast) is sacred ground — only authorized personnel during transmission. Level 2 (commons) is open to everyone and serves as the social heart. Level 5 (armory) requires authorization. Level 7 is restricted and feared — only engineers go down there regularly. The central shaft belongs to everyone; hanging things from the walkways (flags, art, laundry) is a universal form of self-expression.",
  newcomerTreatment: "Suspicious but not hostile. New arrivals are questioned by Commander Vasquez, assigned a bunk on Level 1, and given menial tasks (water carrying, garden maintenance) for their first thirty days. During this probationary period, they're watched constantly but treated fairly. If they're accepted, a small ceremony moves their bunk assignment deeper into the mountain — literally and symbolically moving closer to the heart of the community.",
  accessControl: "The Throat is the primary chokepoint — controlled by armed sentries 24/7 with rotating codes. Each blast door requires two-person authorization. Internal access is tiered: Levels 1–3 are open, Level 4 requires broadcast clearance, Level 5 requires military authorization, Levels 6–7 require engineering or command clearance. The Deep Exit's location is known only to the council and three senior engineers.",

  // Section 7: Narrative Function & Conflict
  storyEventsHere: "Act 1: Kira's daily life — broadcasting, training, arguing with the council about expanding their reach. Act 2 midpoint: A captured corporate scout reveals the Airwell's coordinates have been compromised — the clock starts ticking. The base becomes a pressure cooker of evacuation debates, desperate fortification, and fractured loyalties. Act 3: The siege — corporate forces assault the Throat while the resistance executes a desperate plan to transmit their archive to the world before the base falls.",
  secrets: "Level 6's Archive contains evidence that the Corporate Wars were deliberately engineered — not a civil conflict but a planned consolidation. Mara Calloway has been secretly negotiating with a corporate faction willing to defect. The Deep Exit leads not just to an escape route but to a pre-war government bunker with functioning satellite uplink — the real prize. Commander Vasquez was once a corporate enforcer who defected after committing atrocities he's never confessed.",
  builtInDangers: "Methane accumulation in the lower tunnels (explosion risk). Structural instability — the mountain is slowly shifting, and tremors are increasing. Flooding on Level 7 that could cascade upward if the pumps fail. The ventilation shaft is both a lifeline and a vulnerability — a single incendiary device dropped from above could fill the base with smoke. The Throat's defenses work both ways — in a worst case, the blast doors trap people inside.",
  escapeRoutesTraps: "The Throat's blast doors can seal the entrance but also trap invaders in a kill zone between doors 1 and 2. The Deep Exit is the true escape but requires rebreathers and knowledge of the flooded passages. The shaft opening at the top could support helicopter extraction but is easily targeted from above. Level 5's armory is designed to be sealed and destroyed rather than captured — a dead man's switch only the commander can arm.",
  characterConstraints: "Characters cannot leave quickly — the Throat takes twenty minutes to traverse safely. Communication with the outside world depends on the broadcast equipment on Level 4 — lose it and you lose the mission. The tight vertical layout means sound carries; secrets are hard to keep. The limited exits mean that in a crisis, evacuation is painfully slow. Anyone with claustrophobia or fear of heights is in constant low-grade distress.",

  // Section 8: Location Arc
  stateAtOpening: "Functioning but fragile. The Airwell is alive, humming, defiant — a place of purpose and community. But cracks are showing: the generators struggle, the population strains resources, and the outside world is closing in. It feels like autumn — still beautiful, but you can sense the coming cold.",
  stateAtClimax: "Under siege and tearing at the seams. The Throat is breached, smoke fills Level 1, the blast doors hold but won't hold forever. The broadcast level is still transmitting — Kira's voice going out over the airwaves even as explosions shake the rock. The Airwell becomes both a fortress making its last stand and a megaphone shouting truth at the world.",
  stateAtResolution: "Partially destroyed but symbolically immortal. The physical Airwell is damaged — Level 1 collapsed, the Throat permanently sealed, several levels flooded. But the final broadcast transmitted the Archive to the world, and the core community escaped through the Deep Exit. The Airwell is gone as a base but lives on as a legend — the place where the truth got out.",
  transformationCause: "The siege forces the Airwell to fulfill its ultimate purpose: not to survive forever, but to broadcast long enough for the truth to reach the world. The location transforms from a shelter (defensive, inward-looking) to a weapon (offensive, outward-projecting).",
  transformationStatement: "At the start, the Airwell is a hiding place — a community preserving itself against the world. Through the story, it becomes a battleground where the cost of truth is measured in stone and blood. By the end, it represents the idea that some things are worth more than survival — that a voice, broadcast into the darkness, can outlive the walls that housed it.",

  // Section 9: Theme & Symbolism
  thematicRepresentation: "The Airwell embodies the tension between safety and freedom, shelter and prison, preservation and sacrifice. It asks: what is a home worth if you never leave it? And what is truth worth if no one hears it?",
  recurringMotifs: "Verticality — the shaft as a metaphor for aspiration (looking up to the light) vs. descent (into darkness, into the past, into fear). Broadcasting — the act of sending a voice into silence, hoping someone hears. Water — both life-giving (the underground springs) and threatening (the rising floods). Echoes — sounds in the shaft carry and distort, just like truth in a world of propaganda.",
  symbolicObjects: "The broadcast microphone (Kira's connection to the outside world). Mara Calloway's original blueprints (rolled up, stained, carried like sacred scrolls). The 1947 memorial wall with miners' names (the debt to the past). The column of daylight through the shaft (hope, impermanence, the world above). The Dead Man's switch in the armory (the willingness to destroy what you love rather than let it be corrupted).",
  colorWeatherAssociations: "Interior: warm amber (LED corridors, safety, community), blue-green (bioluminescent moss, the uncanny, the deep places), harsh white (fluorescent work areas, truth, exposure). Exterior: fog (concealment, uncertainty), storms (threat, the siege), clear skies (rare, hope, the stars visible from Level 4 at night).",
  characterMirror: "The Airwell mirrors Kira's arc precisely. Like her, it appears strong but is crumbling from within. Like her, it must choose between self-preservation and self-sacrifice. Like her, its greatest power isn't its defenses — it's its voice. When the Airwell falls but its broadcast survives, it mirrors Kira's own transformation from someone who hides behind walls to someone who steps into the open.",

  // Section 10: Technical & Production Notes
  keyProps: "The broadcast console (a Frankenstein of pre-war radio equipment, military hardware, and improvised circuitry). Mining helmets repurposed as work lights. The wooden handrails — smooth, warm, human. Ration tins used as cups, containers, and decorative objects. Mara's blueprints. The Dead Man's switch (a repurposed mining detonator). The rebreathers stored near the Deep Exit. Kira's personal microphone — dented, taped, irreplaceable.",
  practicalConsiderations: "Lighting is the primary production challenge — every scene needs careful consideration of light source (LEDs, fluorescent, bioluminescent moss, daylight shaft, emergency red). Sound design is critical — the constant ventilation hum, dripping water, and shaft echoes create the base's atmosphere. The vertical nature of the set requires creative shooting angles and awareness of the ever-present shaft opening above or darkness below.",
  realWorldReferences: "Cheyenne Mountain Complex (NORAD) — military use of mountain interiors. Wieliczka Salt Mine (Poland) — underground community spaces with art and architecture. Cu Chi Tunnels (Vietnam) — resistance network in confined spaces. Svalbard Global Seed Vault — preserving knowledge underground. Appalachian coal mining communities — the cultural DNA of the Airwell's inhabitants. Pirate radio stations of the Cold War era — Radio Free Europe as broadcast model.",
  cameraAngleSuggestions: "Vertical shots through the shaft (looking up: hope and freedom; looking down: fear and depth). Tight corridor shots emphasizing claustrophobia. Wide shots of the Level 2 commons showing community life. Low-angle shots of the blast doors emphasizing their weight and permanence. Through-the-microphone shots during broadcasts (intimate, confessional). Dolly shots following the column of daylight as it moves through the shaft during the day.",
  vfxNotes: "Volumetric light for the shaft daylight column (changing color and angle throughout the day). Particle effects for dust, moisture, and condensation on cold surfaces. Subtle screen shake during distant explosions or tremors. Bioluminescent moss glow in deep tunnels (practical + enhanced). Water effects for the flooding sequences on Level 7. The broadcast signal visualized as expanding concentric circles overlaid on exterior establishing shots. Smoke and debris for the siege sequences.",

  // Visual Study — 6 Layer Prompts
  visualEstablishing:
    "Wide aerial establishing shot of the Airwell's mountain location in the Appalachian mountains, 2089. Dense mixed-hardwood forest covering steep mountainsides, morning fog filling the valley below. A single mountain — Blackbone Ridge — dominates the frame, its dark sandstone cliffs partially visible through the trees. No obvious signs of habitation except, if you look carefully, thin wisps of ventilation steam rising from the forested peak and the faintest glint of camouflaged metalwork. The ruins of a small coal-mining town visible in a distant valley. Overcast sky with dramatic cloud breaks. Scale: the mountain should feel massive, ancient, protective. Art style: cinematic wide shot, production-ready environment concept art, matte painting quality.",
  visualArchitectural:
    "Architectural detail study of the Airwell's interior construction. Show the central vertical shaft — 15 meters in diameter, roughly hewn from dark stone with visible coal seams and limestone layers. Metal grating walkways spiral around the shaft, connected by ladders and a single cargo elevator. Salvaged LED strip lights line the walkways in warm amber. Thick steel blast door visible at one tunnel entrance, riveted and scarred. Exposed ventilation ductwork bolted to the rock ceiling. Contrast between the rough natural stone and the improvised human engineering — welded steel brackets, repurposed mining equipment as structural supports, electrical conduit bundled along the walls. Water stains and mineral deposits on the rock face. Art style: detailed architectural reference sheet, cross-section view showing multiple levels.",
  visualInterior:
    "Interior focal point: the Broadcast Level (Level 4) of the Airwell. A circular room carved from rock, centered on a battered broadcast console — a hybrid of vintage radio equipment, military hardware, and improvised circuitry with glowing dials and patched wiring. A worn microphone on a flexible arm, wrapped in electrical tape. The operator's chair is a salvaged car seat bolted to the floor. Walls covered with frequency charts, hand-drawn maps, and photographs of people. A single column of daylight from the shaft above illuminates the room, catching dust motes and casting the equipment in warm light. Coffee mug on the console. Headphones hanging from a hook. The feeling should be: sacred workspace, mission control, confessional booth. Art style: interior concept art, atmospheric rendering, warm amber and cool blue lighting.",
  visualLighting:
    "Lighting and atmosphere study of the Airwell's central shaft viewed from Level 4, showing four conditions. DAWN: golden light pouring down the shaft, illuminating the upper levels in warm tones while lower levels remain in blue shadow. Dust motes floating in the light column. MIDDAY: harsh, flat white light from above, high contrast between the illuminated shaft and dark tunnel mouths. Everything looks exposed, clinical. NIGHT: the shaft becomes a circle of stars visible from below, bioluminescent moss glowing faint blue-green on damp walls, warm LED strips creating pools of amber along the walkways. EMERGENCY: red warning lights flashing, smoke drifting through the shaft, harsh shadows, the blast doors lit from below by emergency floor lights. Art style: mood and lighting reference sheet, four panels, same camera angle, different atmosphere.",
  visualStorytelling:
    "Environmental storytelling detail studies from throughout the Airwell. Panel 1: The 1947 memorial wall on Level 6 — names of 34 dead miners carved into limestone, some with small offerings placed below (a wildflower, a bullet casing, a child's drawing). Panel 2: A sleeping berth on Level 3 — narrow, carved from rock, with a thin mattress, personal items tucked into wall niches (a photo, a book, a small radio), a string of LED fairy lights, and a name scratched into the rock above. Panel 3: The hydroponic gardens on Level 2 — salvaged grow lights over trays of green plants, water recycling tubes, a child's handprint in dried mud on the edge of a planter. Panel 4: Blast damage on Level 1 from the 2081 siege — scorched walls, a sealed tunnel entrance with flowers placed at its base, bullet holes in a steel door. Art style: close-up detail study, cinematic production design, environmental narrative.",
  visualCustom: "",
};
