[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && npm run build"
nixpacksConfigPath = "nixpacks.toml"

[deploy]
startCommand = "NODE_ENV=production node --max-old-space-size=512 dist/index.cjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
